export const syllabus = [
  `"math"{
    "subjects": [
      "Analyzing Graphs",
      "Order of Operations",
      "Powers and Exponents",
      "Writing Expressions",
      "Solving Equations",
      "Using Formulas",
      "A Problem Solving Plan",
      "Problem Solving Strategies",
      "Adding and Subtracting Decimals",
      "Multiplying and Dividing Decimals",
      "Adding and Subtracting Fractions",
      "Multiplying and Dividing Fractions",
      "Adding and Subtracting Integers",
      "Multiplying and Dividing Integers",
      "Rational Numbers",
      "Number Properties",
      "Solving Two Step Equations",
      "Solving Multi-Step Equations",
      "Solving Equations with the Variable on Both Sides",
      "Solving Equations with Rational Numbers",
      "Solving Inequalities Using Addition or Subtraction",
      "Solving Inequalities Using Multiplication or Division",
      "Solving Multi-Step Inequalities",
      "Using Inequalities",
      "Ratios and Rates",
      "Writing and Solving Proportions",
      "Unit Scale and Scale Factor",
      "Scale in Two Dimensions",
      "Scale in Three Dimensions",
      "Customary Units of Measure",
      "Metric Units of Measure",
      "Formulas and Unit Analysis",
      "Fractions, Decimals and Percents",
      "Percents and Proportions",
      "Using the Percent Equation",
      "Percent Increase and Decrease",
      "Consumer Percent",
      "Percent and Statistics",
      "Simple Interest",
      "Compound Interest",
      "Angle Pairs",
      "Triangles and Angles",
      "Quadrilaterals and Angles",
      "Polygons and Angles",
      "Congruent Polygons",
      "Reflections and Symmetry",
      "Translations, Rotations and Tessellations",
      "Similarity and Dilations",
      "Radical Expressions",
      "Rational and Irrational Numbers",
      "The Pythagorean Theorem",
      "Using the Pythagorean Theorem",
      "The Distance Formula",
      "Special Right Triangles",
      "Exploring Trigonometric Ratios",
      "Using Trigonometric Ratios",
      "Area of Polygons",
      "Area of Circles",
      "Solid Figures",
      "Surface Area of Prisms and Cylinders",
      "Surface Area of Pyramids and Cones",
      "Volume of Prisms and Cylinders",
      "Volume of Pyramids and Cones",
      "Surface Area and Volume of Spheres",
      "Relations and Functions",
      "Linear Equations in Two Variables",
      "Using Intercepts",
      "The Slope of a Line",
      "Slope-Intercept Form",
      "Linear Functions",
      "Systems of Linear Functions",
      "Graphs of Linear Inequalities",
      "Measures of Central Tendency and Dispersion",
      "Stem-and-Leaf Plots and Histograms",
      "Box-and-Whisker Plots and Outliers",
      "Scatterplots",
      "Misleading Statistics",
      "Using Data Displays",
      "Collecting Data",
      "Interpreting Data",
      "Counting Methods",
      "Permutations",
      "Combinations",
      "Theoretical and Experimental Probability",
      "Probability and Odds",
      "Conditional Probability",
      "Geometric Probability",
      "Probability and Simulations",
      "Polynomials",
      "Adding and Subtracting Polynomials",
      "Monomials and Powers",
      "Multiplying Binomials",
      "Exploring Parabolas",
      "Quadratic Functions",
      "Exponential Functions",
      "Sequences"
    ]
  }
  "physics":{
    "subjects": [
      "Motion",
      "Position and Displacement",
      "Speed and Velocity",
      "Uniform and Non-Uniform Motion along a Straight Line",
      "Acceleration",
      "Graphical Representation of Motion",
      "Equations of Motion by Graphical Method",
      "Elementary Idea of Uniform Circular Motion",
      "Force",
      "Balanced and Unbalanced Forces",
      "Newtons First Law of Motion",
      "Inertia",
      "Newtons Second Law of Motion",
      "Momentum",
      "Newtons Third Law of Motion",
      "Conservation of Momentum",
      "Gravitation",
      "Universal Law of Gravitation",
      "Acceleration due to Gravity",
      "Equation of Motion",
      "Mass and Weight",
      "Thrust and Pressure",
      "Pressure in Fluids",
      "Archimedes Principle",
      "Relative Density",
      "Work",
      "Energy",
      "Power",
      "Production of Sound",
      "Propagation of Sound",
      "Sound Needs a Medium to Travel",
      "Sound Waves are Longitudinal Waves",
      "Characteristics of Sound Waves",
      "Speed of Sound",
      "Reflection of Sound",
      "Applications of Ultrasound",
      "Structure of Human Ear"
    ]
  }
  
  "biology":{
    "subjects": [
      "Scientific Ways of Thinking",
      "What Is Life Science?",
      "The Scientific Method",
      "The Microscope",
      "Safety in Life Science Research",
      "Characteristics of Living Organisms",
      "Chemistry of Living Things",
      "Classification of Living Things",
      "Life’s Building Blocks",
      "Cell Structures",
      "Transport",
      "Photosynthesis",
      "Cellular Respiration",
      "Cell Division",
      "Reproduction",
      "Protein Synthesis",
      "Mendel's Discoveries",
      "Introduction to Genetics",
      "Advances in Genetics",
      "Darwin’s Theory of Evolution",
      "Evidence for Evolution",
      "The Scale of Evolution",
      "History of Life on Earth",
      "Introduction to Prokaryotes",
      "Bacteria",
      "Archaea",
      "Protists",
      "Fungi",
      "Introduction to Plants",
      "Evolution and Classification of Plants",
      "Plant Responses and Special Adaptations",
      "What Are Animals?",
      "How Animals Evolved",
      "Sponges and Cnidarians",
      "Flatworms and Roundworms",
      "Mollusks and Annelids",
      "Insects and Other Arthropods",
      "Echinoderms and Invertebrate Chordates",
      "Introduction to Vertebrates",
      "Fish",
      "Amphibians",
      "Reptiles",
      "Birds",
      "Mammals",
      "Primates",
      "Understanding Animal Behavior",
      "Types of Animal Behavior",
      "Introduction to the Human Body",
      "The Integumentary System",
      "The Skeletal System",
      "The Muscular System",
      "Food and Nutrients",
      "Choosing Healthy Foods",
      "The Digestive System",
      "Overview of the Cardiovascular System",
      "Heart and Blood Vessels",
      "Blood",
      "The Respiratory System",
      "The Excretory System",
      "The Nervous System",
      "The Senses",
      "The Endocrine System",
      "Infectious Diseases",
      "Noninfectious Diseases",
      "First Two Lines of Defense",
      "Immune System Defenses",
      "Male Reproductive System",
      "Female Reproductive System",
      "Reproduction and Life Stages",
      "Reproductive System Health",
      "What Is Ecology?",
      "Populations",
      "Communities",
      "Ecosystems",
      "Biomes",
      "Flow of Energy",
      "Cycles of Matter",
      "Ecosystem Change",
      "Air Pollution",
      "Water Pollution",
      "Natural Resources",
      "Biodiversity and Extinction"
    ]
  }
  
  `,
  `"math":{
    "subjects": [
      "Equations and Functions",
      "Variable Expressions",
      "Order of Operations",
      "Patterns and Equations",
      "Equations and Inequalities",
      "Functions as Rules and Tables",
      "Functions as Graphs",
      "Problem-Solving Plan",
      "Problem-Solving Strategies: Make a Table and Look for a Pattern",
      "Real Numbers",
      "Integers and Rational Numbers",
      "Adding and Subtracting Rational Numbers",
      "Multiplying and Dividing Rational Numbers",
      "The Distributive Property",
      "Square Roots and Real Numbers",
      "Problem-Solving Strategies: Guess and Check, Work Backward",
      "Equations of Lines",
      "One-Step Equations",
      "Two-Step Equations",
      "Multi-Step Equations",
      "Equations with Variables on Both Sides",
      "Ratios and Proportions",
      "Percent Problems",
      "Graphs of Equations and Functions",
      "The Coordinate Plane",
      "Graphs of Linear Equations",
      "Graphing Using Intercepts",
      "Slope and Rate of Change",
      "Graphs Using Slope-Intercept Form",
      "Direct Variation Models",
      "Linear Function Graphs",
      "Problem-Solving Strategies - Graphs",
      "Writing Linear Equations",
      "Forms of Linear Equations",
      "Equations of Parallel and Perpendicular Lines",
      "Fitting a Line to Data",
      "Predicting with Linear Models",
      "Linear Inequalities",
      "Solving Inequalities",
      "Using Inequalities",
      "Compound Inequalities",
      "Absolute Value Equations and Inequalities",
      "Linear Inequalities in Two Variables",
      "Solving Systems of Equations and Inequalities",
      "Linear Systems by Graphing",
      "Solving Linear Systems by Substitution",
      "Solving Linear Systems by Elimination",
      "Special Types of Linear Systems",
      "Systems of Linear Inequalities",
      "Exponential Functions",
      "Exponent Properties Involving Products",
      "Exponent Properties Involving Quotients",
      "Zero, Negative, and Fractional Exponents",
      "Scientific Notation",
      "Geometric Sequences",
      "Exponential Functions",
      "Applications of Exponential Functions",
      "Polynomials",
      "Addition and Subtraction of Polynomials",
      "Multiplication of Polynomials",
      "Special Products of Polynomials",
      "Polynomial Equations in Factored Form",
      "Factoring Quadratic Expressions",
      "Factoring Special Products",
      "Factoring Polynomials Completely",
      "Quadratic Equations and Quadratic Functions",
      "Graphs of Quadratic Functions",
      "Quadratic Equations by Graphing",
      "Quadratic Equations by Square Roots",
      "Solving Quadratic Equations by Completing the Square",
      "Solving Quadratic Equations by the Quadratic Formula",
      "The Discriminant",
      "Linear, Exponential, and Quadratic Models",
      "Algebra and Geometry Connections",
      "Graphs of Square Root Functions",
      "Radical Expressions",
      "Radical Equations",
      "The Pythagorean Theorem and Its Converse",
      "Distance and Midpoint Formulas",
      "Rational Equations and Functions",
      "Inverse Variation Models",
      "Graphs of Rational Functions",
      "Division of Polynomials",
      "Rational Expressions",
      "Multiplying and Dividing Rational Expressions",
      "Adding and Subtracting Rational Expressions",
      "Solutions of Rational Equations",
      "Probability and Statistics",
      "Theoretical and Experimental Probability",
      "Probability and Permutations",
      "Probability and Combinations",
      "Probability of Compound Events",
      "Measures of Central Tendency and Dispersion",
      "Stem-and-Leaf Plots and Histograms",
      "Box-and-Whisker Plots",
      "Surveys and Samples"
    ]
  }
  
  "physics":{
    "subjects": [
      "Physical World",
      "What is Physics?",
      "Scope and Excitement of Physics",
      "Physics, Technology and Society",
      "Fundamental Forces in Nature",
      "Self Assessments",
      "Home Assignments",
      "Units and Measurements",
      "The International System of Units",
      "Measurement of Length, Mass and Time",
      "Errors in Measurement",
      "Significant Figures",
      "Dimensions of Physical Quantities",
      "Dimensional Formulae and Dimensional Equations",
      "Dimensional Analysis and its Applications",
      "Self Assessments",
      "Kinematics",
      "Frame of Reference and Relative Velocity",
      "Motion in a Straight Line",
      "Rate of Change of Position, Speed and Velocity",
      "Uniform and Non Uniform Motion",
      "Average Speed and Instantaneous Velocity",
      "Acceleration",
      "Position-Time and Velocity-Time Graphs",
      "Scalar and Vector Quantities",
      "Vectors and their Application to Describe Motion",
      "Motion in a Plane",
      "Projectile Motion",
      "Uniform Circular Motion",
      "Self Assessments",
      "Laws of Motion",
      "Force",
      "Aristotle's Fallacy",
      "Newton's First Law of Motion",
      "Newton's Second Law of Motion",
      "Newton's Third Law of Motion",
      "Friction",
      "Free Body Diagrams",
      "Circular Motion",
      "Self Assessments",
      "Work, Power and Energy",
      "Work (Definition)",
      "Work Done by a Constant Force",
      "Work Done by Variable Force",
      "Positive and Negative Work",
      "Work in Terms of Rectangular Components",
      "Energy and its Forms",
      "Kinetic Energy",
      "Work - Energy Theorem",
      "Potential Energy",
      "Conservative Forces and Non Conservative Forces",
      "Collision",
      "Perfectly Elastic Collisions",
      "Inelastic Collisions",
      "Law of Conservation of Energy",
      "Einstein's Relativistic Mass Formula",
      "Power",
      "Self Assessments",
      "Rotational Motion",
      "Rotational Equilibrium and Principle of Moments",
      "Centre of Mass",
      "Moment of Inertia",
      "Torque",
      "Newton's Second Law for Rotation",
      "Angular Momentum",
      "Angular Momentum and Energy for System of Particles",
      "Kinematics of Rotation",
      "Self Assessments",
      "Gravitation",
      "Universal Law Of Gravitation",
      "Acceleration Due To Gravity",
      "Gravitational Field Intensity",
      "Gravitational Potential",
      "Gravitational Potential Energy",
      "Orbital Velocity",
      "Total Energy of the Satellite",
      "Escape Velocity",
      "Kepler's Laws of Planetary Motion",
      "Self Assessments",
      "Mechanical Properties of Solids",
      "Elastic Behaviour",
      "Stress and Strain",
      "Hooke's Law and Elastic Limit",
      "Shear and Modulus of Rigidity",
      "Young's Modulus of Elasticity",
      "Bulk Modulus of Elasticity",
      "Poisson's Ratio",
      "Elastic Potential Energy",
      "Self Assessments",
      "Mechanical Properties of Fluids",
      "Pressure",
      "Pascal's Law and Its Application",
      "Atmospheric Pressure and Gauge Pressure",
      "Flow of Fluids",
      "Bernoulli's Principle and Its Applications",
      "Viscosity",
      "Surface Tension",
      "Drops and Bubbles",
      "Capillary Rise",
      "Self Assessments",
      "Thermal Properties of Matter",
      "Temperature and Heat Energy",
      "Thermometer and Measurement of Temperature",
      "Ideal Gas Equation and Absolute Temperature",
      "Thermal Expansion",
      "Specific Heat and Calorimetry",
      "Change of State",
      "Heat Transfer",
      "Newton's Law of Cooling",
      "Stefan's Law",
      "Wien's Displacement Law",
      "Self Assessments",
      "Thermodynamics",
      "Behaviour of Gases",
      "Thermodynamic Processes",
      "Thermal Equilibrium and Zeroth Law of Thermodynamics",
      "First Law of Thermodynamics",
      "Second Law of Thermodynamics",
      "Heat Engine",
      "Self Assessments",
      "Kinetic Theory",
      "Equation of State of a Perfect Gas",
      "Kinetic Theory of Gases",
      "Kinetic Theory and Temperature",
      "Thermal Energy",
      "Law of Equipartition of Energy",
      "Self Assessments",
      "Oscillations",
      "Oscillation and Vibration",
      "Periodic Motion",
      "Periodic Function and its Application to Describe Equation of Motion",
      "Simple Harmonic Motion",
      "Simple Harmonic Motion and Uniform Circular Motion",
      "Oscillations of a Spring",
      "Energy in SHM",
      "Simple Pendulum Derivation of Expression for its Time Period",
      "Free Forced and Damped Oscillation",
      "Resonance",
      "Velocity and Acceleration in Simple Harmonic Motion",
      "Self Assessments",
      "Waves",
      "Wave Motion",
      "Transverse and Longitudinal Waves, Speed of Wave Motion",
      "Displacement Relation for a Progressive Wave",
      "Reflection of Waves",
      "Principle of Superposition of Waves",
      "Standing Waves in Strings and Organ Pipes",
      "Beats",
      "Doppler Effect",
    ]
  }
  "biology":{
    "subjects": [
      "What is Biology?",
      "Science and the Natural World",
      "Biology: The Study of Life",
      "The Chemistry of Life",
      "Matter and Organic Compounds",
      "Biochemical Reactions",
      "Water, Acids, and Bases",
      "Cellular Structure and Function",
      "Introduction to Cells",
      "Cell Structures",
      "Cell Transport and Homeostasis",
      "Photosynthesis and Cellular Respiration",
      "Energy for Life",
      "Photosynthesis: Sugar as Food",
        "Powering the Cell: Cellular Respiration",
      "Anaerobic Respiration",
      "The Cell Cycle, Mitosis, and Meiosis",
      "Cell Division and the Cell Cycle",
      "Chromosomes and Mitosis",
      "Reproduction and Meiosis",
      "Gregor Mendel and Genetics",
      "Mendel's Investigations",
      "Mendelian Inheritance",
      "Molecular Genetics: From DNA to Proteins",
      "DNA and RNA",
      "Protein Synthesis",
      "Mutation",
      "Regulation of Gene Expression",
      "Human Genetics and Biotechnology",
      "Human Chromosomes and Genes",
      "Human Inheritance",
      "Biotechnology",
      "Life: From the First Organism Onward",
      "Earth Forms and Life Begins",
      "The Evolution of Multicellular Life",
      "Classification",
      "The Theory of Evolution",
      "Darwin and the Theory of Evolution",
      "Evidence for Evolution",
      "Microevolution and the Genetics of Populations",
      "Macroevolution and the Origin of Species",
      "The Principles of Ecology",
      "The Science of Ecology",
      "Recycling Matter",
      "Biomes",
      "Communities and Populations",
      "Community Interactions",
      "Characteristics of Populations",
      "Human Population Growth",
      "The Biodiversity Crisis",
      "Natural Resources and Climate Change",
      "References",
      "Microorganisms: Prokaryotes and Viruses",
      "Prokaryotes",
      "Viruses",
      "Eukaryotes: Protists and Fungi",
      "Introduction to Protists",
      "Types of Protists",
      "Introduction to Fungi",
      "Ecology of Fungi",
      "Protists, Fungi, and Human Disease",
      "Plant Evolution and Classification",
      "Introduction to the Plant Kingdom",
      "Four Types of Modern Plants",
      "Plant Biology",
      "Plant Tissues and Growth",
      "Plant Organs: Roots, Stems, and Leaves",
      "Variation in Plant Life Cycles",
      "Plant Adaptations and Responses",
      "Introduction to Animals",
      "Overview of Animals",
      "Overview of Invertebrates",
      "References",
      "From Sponges to Invertebrate Chordates",
      "Sponges, Cnidarians, Flatworms, and Roundworms",
      "Mollusks and Annelids",
      "Arthropods and Insects",
      "Echinoderms and Invertebrate Chordates",
      "References",
      "From Fish to Birds",
      "Overview of Vertebrates",
      "Fish",
      "Amphibians",
      "Reptiles",
      "Birds",
      "References",
      "Mammals and Animal Behavior",
      "Mammalian Traits",
      "Reproduction in Mammals",
      "Evolution and Classification of Mammals",
      "Overview of Animal Behavior",
      "Introduction to the Human Body: Bones, Muscles, and Skin",
      "Organization of the Human Body",
      "The Skeletal System",
      "The Muscular System",
      "The Integumentary System",
      "The Nervous and Endocrine Systems",
      "The Nervous System",
      "The Endocrine System",
      "The Circulatory, Respiratory, Digestive, and Excretory Systems",
      "The Circulatory System",
      "The Respiratory System",
      "The Digestive System",
      "The Excretory System",
      "The Immune System and Disease",
      "Nonspecific Defenses",
      "The Immune Response",
      "Immune System Diseases",
      "Environmental Problems and Human Health",
      "Reproduction and Human Development",
      "Male Reproductive System",
      "Female Reproductive System",
      "From Fertilization to Old Age",
      "Sexually Transmitted Infections",
      "Biology Glossary",
    ]
  }
  
  `,
  `
  "math":{
    "subjects":[
        "Relations and Functions",
        "Types of Relations",
        "Types of Functions",
        "Composition of Functions and Invertible Functions",
        "Binary Operations",
        
        "Inverse Trigonometric Functions",
        "Inverse Trigonometric Functions and Principal Value Branch",
        "Properties and Identities of Inverse Trigonometric Functions",
        "Simplest Form of Inverse Trigonometric Functions by using Substitution",
        "Inverse Trigonometric Equations",
        
        "Matrices",
        "Matrix",
        "Types of Matrices",
        "Operations on Matrices",
        "Transpose of a Matrix",
        "Symmetric and Skew Symmetric Matrices",
        "Elementary Operation (Transformation) of a Matrix",
        
        "Determinants",
        "Determinants",
        "Properties of Determinants",
        "Area of a Triangle",
        "Minors and Cofactors",
        "Adjoint and Inverse of a Matrix",
        "Applications of Determinants and Matrices",
        
        "Continuity and Differentiability",
        "Continuity",
        "Differentiability",
        "Derivatives of Composite Functions (Chain Rule)",
        "Derivatives of Implicit Functions",
        "Derivatives of Inverse Trigonometric Functions",
        "Derivatives of Exponential and Logarithmic Functions",
        "Logarithmic Differentiation",
        "Derivatives of Parametric Functions",
        "Second Order Derivatives",
        "Mean Value Theorems",
        
        "Application of Derivatives",
        "Rate of Change of Quantities",
        "Increasing and Decreasing Functions",
        "Tangents and Normals",
        "Approximation",
        "Maxima and Minima",
        
        "Definite Integrals",
        "Definite Integrals as the Limit of a Sum",
        "Fundamental Theorem of Calculus",
        "Evaluation of Definite Integrals by Substitution",
        "Properties of Definite Integrals",
        
        "Indefinite Integrals",
        "Integration as Anti-Derivative",
        "Integration by Substitution",
        "Integration Using Trigonometric Identities",
        "Integrals of Some Particular Functions",
        "Integration by Partial Fractions",
        "Integration by Parts",
        
        "Applications of Integrals",
        "Area Under Simple Curves",
        "Area Between Two Curves",
        
        "Differential Equations",
        "Order and Degree of a Differential Equation",
        "General and Particular Solution of a Differential Equation",
        "Formation of Differential Equation",
        "Solution of Differential Equation with Variable Separable",
        "Solution of Homogeneous Differential Equation",
        "Solution of Linear Differential Equation",
        "Applications of Differential Equation",
        
        "Vector Algebra",
        "Position Vector, Direction Cosines and Ratios",
        "Types of Vectors",
        "Addition of Vectors",
        "Multiplication of a Vector by a Scalar",
        "Scalar or Dot Product of Two Vectors",
        "Vector or Cross Product of Two Vectors",
        "Scalar Triple Product",
        "Real World Applications of Vectors",
        
        "Three Dimensional Geometry",
        "Direction Ratios and Direction Cosines of a Line",
        "Equation of a Line in Space",
        "Angle between Two Lines",
        "Shortest Distance between Two Lines",
        "Equation of a Plane in Space",
        "Coplanarity of Two Lines",
        "Angle Between Two Planes",
        "Distance of a Point from a Plane",
        "Angle between a Line and a Plane",
        
        "Linear Programming",
        "Linear Programming Problem and its Mathematical Formulation",
        "Real World Applications",
        
        "Probability",
        "Conditional Probability",
        "Independent Events",
        "Multiplication Theorem on Probability",
        "Bayes' Theorem",
        "Random Variables and Probability Distribution",
        "Bernoulli's Trials and Binomial Distribution"
    ]
    }
  
  "physics":{
    "subjects":[
        "Conductors, Insulators, and Charging by Induction",
        "Basic Properties of Charge",
        "Coulomb's Law",
        "Principle of Superposition of Charges",
        "Electric Field and Electric Field Lines",
        "Electric Dipole",
        "Electric Flux, Gauss's Law, and Applications",
        "Electrostatic Potential",
        "Electric Potential due to a Point Charge and Electric Dipole",
        "Equipotential Surfaces",
        "Potential Energy of Point Charges",
        "Electrostatics of Conductors",
        "Capacitors and their Properties",
        "Dielectrics",
        "Electric Current",
        "Ohm's Law",
        "Drift of Electrons and Origin of Resistivity",
        "Mobility of Charge Carriers",
        "Limitations of Ohm’s Law",
        "Resistivity of Different Materials",
        "Temperature Dependence of Resistivity",
        "Combination of Resistors (Series and Parallel)",
        "Electrical Energy and Power",
        "Electrical Cells, EMF, and Internal Resistance",
        "Cells in Series and Parallel",
        "Kirchhoff’s Rules",
        "Wheatstone Bridge",
        "Meter Bridge",
        "Potentiometer",
        "Magnetic Field due to a Current Element (Biot-Savart Law)",
        "Ampere’s Circuital Law",
        "Lorentz Force",
        "Motion in a Magnetic Field",
        "Motion in Combined Electric and Magnetic Fields",
        "Cyclotron",
        "Force Between Two Parallel Currents",
        "Torque on a Current-Carrying Loop",
        "Magnetic Moment of a Revolving Electron",
        "Moving Coil Galvanometer",
        "The Bar Magnet",
        "Magnetism and Gauss's Law",
        "Earth’s Magnetic Field",
        "Magnetic Properties of Materials",
        "Permanent Magnets and Electromagnets",
        "Faraday’s Experiments",
        "Magnetic Flux and Faraday’s Law",
        "Lenz’s Law and Energy Conservation",
        "Motional Electromotive Force (Motional EMF)",
        "Energy Considerations in Induction",
        "Eddy Currents",
        "Self-Induction",
        "Mutual Inductance",
        "A.C. Generator",
        "Transformer",
        "AC Voltage Applied to a Resistor",
        "AC Voltage Applied to an Inductor",
        "AC Voltage Applied to a Capacitor",
        "AC Voltage Applied to an LCR Circuit",
        "Power in AC Circuits",
        "LC Oscillations",
        "Displacement Current",
        "Electromagnetic Waves",
        "Electromagnetic Spectrum",
        "Radio Waves",
        "Microwaves",
        "Light Waves",
        "X-Rays",
        "Gamma Rays",
        "Laws of Reflection",
        "Reflection of Light by Spherical Mirrors",
        "Refraction of Light",
        "Total Internal Reflection",
        "Refraction at Spherical Surfaces and by Lenses",
        "Refraction Through a Prism",
        "Dispersion Through a Prism",
        "Optical Instruments",
        "Huygens' Principle",
        "Reflection and Refraction of Plane Waves using Huygens' Principle",
        "Coherent and Incoherent Addition of Waves - Principle of Superposition",
        "Interference of Light Waves and Young's Experiment",
        "Diffraction",
        "Resolving Power of Optical Instruments",
        "The Validity of Ray Optics",
        "Polarization",
        "Dual Nature of Radiation",
        "Hertz and Lenard's Observations",
        "Photoelectric Effect",
        "Einstein’s Photoelectric Equation",
        "Matter Waves - Wave Nature of Particles",
        "De Broglie Relation",
        "Davisson-Germer Experiment",
        "Alpha Particle Scattering Experiment",
        "Rutherford’s Nuclear Model of Atom",
        "Bohr Model of Hydrogen Atom",
        "Composition and Size of the Nucleus",
        "Radioactivity",
        "Radioactivity Decay Laws",
        "Mass-Energy Relation, Mass Defect",
        "Binding Energy Per Nucleon and its Variation with Atomic Number",
        "Nuclear Force",
        "Nuclear Fission",
        "Nuclear Fusion",
        "Half-Life and Decay Constant",
        "Atomic Spectra",
        "Energy States and Hydrogen Spectrum"
    ]
    
}

"biology":{
    "subjects": [
      "Reproduction in Organisms",
      "Reproduction",
      "Asexual Reproduction",
      "Sexual Reproduction",
      "Asexual vs. Sexual Reproduction",
      "Sexual Reproduction in Flowering Plants",
      "Flower - A Fascinating Organ of Angiosperms (Parts of a Flower)",
      "Ovules and Pollen Grains",
      "Pollination",
      "Life Cycle of an Angiosperm",
      "Seed",
      "Seeds and Seed Dispersal",
      "Human Reproduction",
      "Human Reproductive System",
      "Male Reproductive Structures",
      "Male Reproductive Development",
      "Female Reproductive Structures",
      "Female Reproductive Development",
      "Gametogenesis",
      "Human Sperm",
      "Human Egg Cells",
      "Menstrual Cycle",
      "Fertilization, Cleavage and Implantation",
      "Growth and Development of the Embryo",
      "Fetus, Growth and Development",
      "Fetal Development and the Placenta",
      "Pregnancy and Childbirth",
      "Reproductive Health",
      "Reproductive Health - Problems and Strategies",
      "Population Explosion and Birth Control Methods",
      "Medical Termination of Pregnancy",
      "Sexually Transmitted Disease",
      "Infertility",
      "Non-Infectious Reproductive System Disorders",
      "Assisted Reproductive Strategies - ZIFT, Test Tube Babies, GIFT",
      "Principles of Inheritance and Variation - Part I",
      "Gregor Mendel and Genetics",
      "Mendel's Laws and Genetics",
      "Mendel's Pea Plants",
      "Mendel's First Set of Experiments",
      "Mendel's Second Set of Experiments",
      "Probability and Inheritance",
      "Punnett Squares",
      "Test Cross",
      "Non-Mendelian Inheritance",
      "Pleiotropy and Epistasis",
      "Principles of Inheritance and Variation - Part II",
      "Human Chromosomes and Genes",
      "Genetic Linkage",
      "Mendelian Inheritance in Humans",
      "Sex-Linked Traits",
      "Mutations",
      "Chromosomal Disorders",
      "Molecular Basis of Inheritance - Part I",
      "Central Dogma of Molecular Biology",
      "The DNA Double Helix",
      "Discovery of DNA - The Hereditary Material",
      "DNA Replication",
      "RNA",
      "The Genetic Code",
      "Protein Synthesis",
      "Molecular Basis of Inheritance - Part II",
      "Gene Expression",
      "Prokaryotic Gene Regulation - Lac Operon Concept",
      "Eukaryotic Gene Regulation",
      "Human Genome Project",
      "DNA Fingerprinting",
      "Evolution - Part I",
      "Origin of Earth",
      "Origin and Evolution of Life",
      "First Organic Molecules - Miller and Urey Experiment",
      "Formation of First Cells",
      "Evolution of Life - Darwin's Theory of Evolution",
      "Evolution of Eukaryotes",
      "Evidences for Evolution",
      "Paleontological Evidence",
      "Comparative Anatomy - Homologous, Analogous, and Vestigial Structures",
      "Embryological Evidences",
      "Molecular Evidence of Evolution",
      "Evolution - Part II",
      "Biogeography and Adaptive Radiations",
      "Darwin's Voyage of the Beagle, His Theory and Observations",
      "Influences on Darwin - Earlier Thinkers Who Influenced Darwin",
      "Theory of Evolution by Natural Selection",
      "Hardy-Weinberg Theorem",
      "Forces of Evolution - Gene Flow, Genetic Drift, Founder's Effect",
      "Effect of Natural Selection - Stabilizing, Directional, Disruptive",
      "Mechanisms of Evolution - Population Genetics",
      "Human Health and Diseases - I",
      "Pathogens and How They Spread",
      "Bacteria and Diseases",
      "Viruses and Human Disease",
      "Protozoans and Human Diseases",
      "Roundworms and Diseases",
      "Fungi and Human Disease",
      "Immunity - Active and Passive",
      "Barriers to Pathogens - First Defense",
      "Inflammatory Response and Leukocytes - Second Defense",
      "Humoral Immune Response",
      "Cell-Mediated Immune Response",
      "Vaccination and Immunisation",
      "Human Health and Diseases - II",
      "Autoimmune Diseases",
      "Immunodeficiency",
      "Allergies",
      "HIV and AIDS",
      "Cancer",
      "Adolescence",
      "Drugs and Drug Abuse",
      "Alcohol and Alcohol Abuse",
      "Effects of Drug and Alcohol Abuse and Prevention",
      "Microbes in Human Welfare",
      "Bacteria and Humans - Beneficial and Harmful Relationships",
      "Helpful Bacteria",
      "Human Uses of Fungi - Use of Antibiotic Penicillin",
      "Viruses in Research and Medicine",
      "Microbes in Sewage Treatment",
      "Microbes in Biogas Production",
      "Microbes as Biocontrol Agents - Example Bt Cotton",
      "Microbes as Biofertilizers",
      "Biotechnology: Principles and Processes",
      "Biotechnology - Basic Principle and Formation of Recombinant DNA",
      "An Important Process of rDNA Technology - Polymerase Chain Reaction",
      "Gene Cloning in Detail",
      "Bioreactors",
      "Biotechnology and its Applications",
      "Applications of Biotechnology in Agriculture",
      "Applications of DNA Technology in Forensic Science",
      "Biotechnological Applications in Medicine",
      "Transgenic Animals",
      "Ethical, Legal and Social Issues of Biotechnology",
      "Organisms and Populations - I",
      "Organism and its Environment",
      "Major Abiotic Factors",
      "Responses to Abiotic Factors",
      "Adaptations",
      "Population Attributes",
      "Population Growth",
      "Life History Variation",
      "Organisms and Populations - II",
      "Interdependence of Living Things - Population Interactions",
      "Symbiotic Relationships - Mutualism, Commensalism, and Parasitism",
      "Competition",
      "Predation",
      "Ecosystem",
      "Energy Flow",
      "Food Chains and Food Webs",
      "Ecological Pyramids",
      "Trophic Levels",
      "Ecological Succession",
      "Biogeochemical Cycles",
      "Biodiversity and Conservation",
      "Environmental Issues - I",
      "Air Pollution",
      "Water Pollution",
      "Environmental Issues - II",
      "Global Climate Change - Greenhouse Effect, Global Warming",
      "Ozone Depletion",
      "Deforestation and Habitat Destruction"
    ]
  }
`
]
export function calcSyllabus(lastYear:number,yearsMissed:number){
    let text = ""
    for(let i=(lastYear-10)+1;i++;i<yearsMissed){
        text+=syllabus[i]
    }
    return text
}
